# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Kiko Plus"



author:
  name:             "Vincent BOURDON"
  phone:            "06.45.78.08.81"
  twitter:          "@evilznet"
  github:           "github.com/evilz"
  blog:             "www.evilznet.com"
  linkedin:         your-id
  email:            "evilznet@gmail.com"
  jobtitle:         ".net developer"
  story:            "prout"

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "your-id"

# URL
#url:                "https://AWEEKJ.github.io" # the base hostname & protocol for your site
url:                "http://localhost:4000" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/AWEEKJ/Kiko-plus"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"



exclude:            [vendor]
